# Generated by Django 4.1.3 on 2022-12-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0002_alter_document_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Man', 'Manual'), ('Proc', 'Procedure'), ('Spec', 'Specification'), ('Form', 'Form'), ('WI', 'Working Instruction')], default='Not Specified', max_length=50),
        ),
    ]
