# Generated by Django 4.1.3 on 2022-12-11 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0003_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_distributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='validity',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Man', 'Manual'), ('Proc', 'Procedure'), ('Spec', 'Specification'), ('Form', 'Form'), ('WI', 'Working Instruction')], default='-------', max_length=5),
        ),
    ]
