# Generated by Django 4.1.3 on 2022-12-12 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0005_document_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='validity',
            new_name='validity_date',
        ),
    ]
