# Generated by Django 4.1.3 on 2022-12-12 05:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_alter_departement_options_alter_position_options_and_more'),
        ('documentManagement', '0006_rename_validity_document_validity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='distribution',
            field=models.ManyToManyField(to='base.departement'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='validity_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
