# Generated by Django 4.1.3 on 2022-12-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0007_document_distribution_document_document_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='document_name',
        ),
    ]
