# Generated by Django 4.1.3 on 2022-12-12 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentManagement', '0010_document_document_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='mr',
        ),
        migrations.AddField(
            model_name='document',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
