# Generated by Django 4.1.3 on 2022-12-16 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0012_alter_document_document_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': []},
        ),
    ]
