# Generated by Django 4.1.3 on 2022-12-28 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0013_alter_document_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['owner']},
        ),
    ]
