# Generated by Django 4.1.3 on 2023-01-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0014_alter_document_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='document',
            name='reviewer',
        ),
    ]
