# Generated by Django 4.1.3 on 2023-01-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0015_remove_document_approver_remove_document_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Man', 'Manual'), ('Proc', 'Procedure'), ('Spec', 'Specification'), ('Form', 'Form'), ('WI', 'Working Instruction')], default='-------', max_length=50),
        ),
    ]
