# Generated by Django 4.1.3 on 2022-12-04 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_departement_position_user_departement_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='departement',
        ),
        migrations.AddField(
            model_name='position',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.departement'),
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
