# Generated by Django 4.1.3 on 2023-01-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_departement_options_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departement',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name']},
        ),
    ]
